venv:
	python3.10 -m venv myenv

activate:
	. myenv/bin/activate

install:
	pip3 install -r requirements.txt

run:
	python3 script.py >> result.txt

clean:
	rm -rf myenv result.txt



